#Config File example
save_dir: ./demo/workspace/model_new_pan
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.5x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [176, 352, 704]
      out_channels: 128
      start_level: 0
      num_outs: 3
      task : multi
    head:
      name: NanoDetHead
      num_classes: 7 #Please fill in the number of categories (not include background category)
      input_channel: 128
      feat_channels: 128
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: &class_names ['go_ahead', 'turn_left', 'turn_right', 'no_turn_left', 'no_turn_right','stop','car']  #Please fill in the category names (not include background category)
data:
  train:
    name: xml_dataset
    class_names: *class_names
    img_path: ./dataset/train/image #Please fill in train image path
    ann_path: ./dataset/train/annotations  #Please fill in train xml path
    seg_path: ./dataset/train/segment
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      hsv: [0.1,0.1,0.1]
      flip: 0
      brightness: 0.5
      contrast: [0.8, 1.2]
      hue: [0.8, 1.2]
      value: [0.5, 1.5]
      saturation: [0.8, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: xml_dataset
    class_names: *class_names
    img_path: ./dataset/val/image #Please fill in val image path
    ann_path: ./dataset/val/annotations #Please fill in val xml path
    seg_path: ./dataset/val/segment
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: None
  workers_per_gpu: 1
  batchsize_per_gpu: 2
schedule:
#  resume:
#  load_model: /content/drive/MyDrive/nanodet-main/demo/workspace/model_best/model_best.ckpt
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 190
  lr_schedule:
    name: MultiStepLR
    milestones: [130,160,175,185]
    gamma: 0.1
  val_intervals: 1
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 1
